import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Navbar from "@/components/Navbar";
import { Sofia_Sans } from "next/font/google"; // 👈 import font
import ProgressBar from "@/components/ProgressBar"; // 👈 import

// Configure the font
const sofiaSans = Sofia_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "700"], // pick the weights you need
});

// Metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Layout
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      {/* 👇 apply font globally */}
      <body className={sofiaSans.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <ProgressBar />
          <Navbar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
